# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "F:\\OnlineWebAndService"
      dockerfile: "Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "F:\\OnlineWebAndService\\Api:/app:rw"
    - "F:\\OnlineWebAndService:/src:rw"
    - "C:\\Users\\psydu\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
